Comando_Index
alter index  IDX_N0045 on dbo.CAMINHAO_PROGRAMACAO_ITEM reorganize
alter index  IDX_N1010 on dbo.CAMINHAO_PROGRAMACAO rebuild
alter index  IDX_PEDIVENDEXCL_010 on dbo.PEDIDO_VENDA_EXCLUSAO rebuild
alter index  IDX_TAGMODU_NOMEMAQU on dbo.SISTEMA_SUPERVISAO rebuild
alter index  IDX_N00570 on dbo.PEDIDO_DEVOLUCAO_VENDA_ITEM rebuild
alter index  IDX_N00529 on dbo.NOTA_FISCAL reorganize
alter index  IDX_N00531 on dbo.NOTA_FISCAL rebuild
alter index  IDX_N00532 on dbo.NOTA_FISCAL rebuild
alter index  IDX_N1084 on dbo.NOTA_FISCAL reorganize
alter index  IDX_N1085 on dbo.NOTA_FISCAL reorganize
alter index  IDX_N1086 on dbo.NOTA_FISCAL reorganize
alter index  IDX_N2000 on dbo.NOTA_FISCAL rebuild
alter index  IDX_NF_SERIE_01 on dbo.NOTA_FISCAL reorganize
alter index  IDX_SEQUPROD_001 on dbo.PRODUCAO_SEQUESTRO rebuild
alter index  IDX_SEQUPROD_002 on dbo.PRODUCAO_SEQUESTRO rebuild
alter index  IDX_SEQUPROD_003 on dbo.PRODUCAO_SEQUESTRO rebuild
alter index  IDX_SEQUPROD_004 on dbo.PRODUCAO_SEQUESTRO reorganize
alter index  IDX_SEQUPROD_005 on dbo.PRODUCAO_SEQUESTRO rebuild
alter index  IDX_N00623 on dbo.PEDIDO_VENDA rebuild
alter index  IDX_PEDIVEND_031 on dbo.PEDIDO_VENDA rebuild
alter index  IDX_PEDIVEND_037 on dbo.PEDIDO_VENDA reorganize
alter index  IDX_UNQPALEEXPE on dbo.EXPEDICAO_PALETE reorganize
alter index  IDX_N00688 on dbo.PEDIDO_VENDA_NOTA_FISCAL reorganize
alter index  IDX_N00689 on dbo.PEDIDO_VENDA_NOTA_FISCAL reorganize
alter index  UNQ_MATEINTE on dbo.MATERIAL_EMBALAGEM_DEFINICAO rebuild
alter index  MATERIAL_EMBALAGEM_DEFI_IDX_VW_PRO125 on dbo.MATERIAL_EMBALAGEM_DEFINICAO rebuild
alter index  IDX_REPOREGIPROD_002 on dbo.PRODUCAO_REGISTRO_REPOSITORIO reorganize
alter index  IDX_REPOREGIPROD_004 on dbo.PRODUCAO_REGISTRO_REPOSITORIO reorganize
alter index  IDX_REPOREGIPROD_005 on dbo.PRODUCAO_REGISTRO_REPOSITORIO reorganize
alter index  IDX_REPOREGIPROD_010 on dbo.PRODUCAO_REGISTRO_REPOSITORIO reorganize
alter index  IDX_REPOREGIPROD_INVEPROD01 on dbo.PRODUCAO_REGISTRO_REPOSITORIO reorganize
alter index  PRODUCAO_REGISTRO_REPOSITORIO_IDX_VW_PRO125 on dbo.PRODUCAO_REGISTRO_REPOSITORIO reorganize
alter index  IDX_N00429 on dbo.MATERIAL_ALMOXARIFADO reorganize
alter index  IDX_N00430 on dbo.MATERIAL_ALMOXARIFADO rebuild
alter index  IDX_N00431 on dbo.MATERIAL_ALMOXARIFADO rebuild
alter index  UNQ_MATEALMO on dbo.MATERIAL_ALMOXARIFADO rebuild
alter index  UN_MATEALMO_ITEMENTRMATE on dbo.MATERIAL_ALMOXARIFADO reorganize
alter index  IDX_MATEALMO_EMBAMATEALMO on dbo.MATERIAL_ALMOXARIFADO reorganize
alter index  IDX_MATEEMBA_06 on dbo.MATERIAL_EMBALAGEM_FILIAL rebuild
alter index  IDX_MATEEMBAFILI_02 on dbo.MATERIAL_EMBALAGEM_FILIAL rebuild
alter index  IDX_MATEEMBAFILI_03 on dbo.MATERIAL_EMBALAGEM_FILIAL rebuild
alter index  MATERIAL_EMBALAGEM_FILI_IDX_VW_PRO125 on dbo.MATERIAL_EMBALAGEM_FILIAL rebuild
alter index  IDX_TOTAREGIPROD_010 on dbo.PRODUCAO_REGISTRO_TOTAL reorganize
alter index  IDX_TOTAREGIPROD_011 on dbo.PRODUCAO_REGISTRO_TOTAL reorganize
alter index  IDX_N0050 on dbo.CIDADE reorganize
alter index  UNQ_DIARTURNPROD_FILIDATAUNID on dbo.PRODUCAO_TURNO_DIARIO rebuild
alter index  PRODUCAO_TURNO_DIARIO_IDX_VW_PRO125 on dbo.PRODUCAO_TURNO_DIARIO rebuild
alter index  IDX_N00534 on dbo.NOTA_FISCAL_BASE_ICMS reorganize
alter index  IDX_N00934 on dbo.SCT_REC_JANELA reorganize
alter index  IDX_N00935 on dbo.SCT_REC_JANELA reorganize
alter index  IDX_N00936 on dbo.SCT_REC_JANELA reorganize
alter index  IDX_GN_ITEMENDEALMO on dbo.ALMOXARIFADO_ENDEREC_ITEM rebuild
alter index  IDX_N00930 on dbo.SCT_JANELA rebuild
alter index  IDX_N00931 on dbo.SCT_JANELA rebuild
alter index  IDX_N00777 on dbo.PRODUCAO_INVENTARIO rebuild
alter index  IDX_N00778 on dbo.PRODUCAO_INVENTARIO rebuild
alter index  IDX_N00779 on dbo.PRODUCAO_INVENTARIO rebuild
alter index  IDX_N10136 on dbo.PRODUCAO_INVENTARIO rebuild
alter index  IDX_N10137 on dbo.PRODUCAO_INVENTARIO rebuild
alter index  IDX_N10138 on dbo.PRODUCAO_INVENTARIO rebuild
alter index  IDX_N001004 on dbo.TRANSPORTADOR_VEICULO rebuild
alter index  IDX_N001005 on dbo.TRANSPORTADOR_VEICULO rebuild
alter index  IDX_N001006 on dbo.TRANSPORTADOR_VEICULO rebuild
alter index  IDX_REGIPESASAID_002 on dbo.PESAGEM_REGISTRO_SAIDA reorganize
alter index  IDX_REGIPESASAID_003 on dbo.PESAGEM_REGISTRO_SAIDA rebuild
alter index  IDX_ITEMDESTREGIPROD_REGIPROD on dbo.PRODUCAO_REGISTRO_DEST_ITEM reorganize
alter index  IDX_REGIPRODDESTITEN on dbo.PRODUCAO_REGISTRO_DEST_ITEM reorganize
alter index  MATERIAL_IDX_VW_PRO125 on dbo.MATERIAL rebuild
alter index  IDX_N00926 on dbo.SCT_GR_US rebuild
alter index  IDX_N00927 on dbo.SCT_GR_US rebuild
alter index  IDX_N00928 on dbo.SCT_GR_US rebuild
alter index  IDX_N00929 on dbo.SCT_GR_US rebuild
alter index  IDX_N00299 on dbo.FORNECEDOR rebuild
alter index  IDX_N00300 on dbo.FORNECEDOR rebuild
alter index  IDX_N00301 on dbo.FORNECEDOR rebuild
alter index  IDX_N00302 on dbo.FORNECEDOR rebuild
alter index  IDX_N00303 on dbo.FORNECEDOR rebuild
alter index  IDX_N00304 on dbo.FORNECEDOR rebuild
alter index  IDX_N00305 on dbo.FORNECEDOR rebuild
alter index  IDX_N00306 on dbo.FORNECEDOR rebuild
alter index  IDX_N00307 on dbo.FORNECEDOR rebuild
alter index  IDX_N00308 on dbo.FORNECEDOR rebuild
alter index  IDX_N00309 on dbo.FORNECEDOR rebuild
alter index  IDX_N00310 on dbo.FORNECEDOR rebuild
alter index  IDX_N00311 on dbo.FORNECEDOR rebuild
alter index  IDX_N1055 on dbo.FORNECEDOR rebuild
alter index  IDX_N1056 on dbo.FORNECEDOR rebuild
alter index  IDX_N1057 on dbo.FORNECEDOR rebuild
alter index  IDX_N1058 on dbo.FORNECEDOR rebuild
alter index  IDX_DIREUSU3 on dbo.SCT_DIREITOS_US reorganize
alter index  IDX_N00910 on dbo.SCT_DIREITOS_US reorganize
alter index  IDX_SCTDIREUS_010 on dbo.SCT_DIREITOS_US reorganize
alter index  IDX_N00613 on dbo.PEDIDO_ENTRADA_NOTA_FISCAL rebuild
alter index  IDX_N00614 on dbo.PEDIDO_ENTRADA_NOTA_FISCAL rebuild
alter index  IDX_N00615 on dbo.PEDIDO_ENTRADA_NOTA_FISCAL rebuild
alter index  IDX_ITEMESTOREGIPROD_GERAPRODREGIESTO on dbo.PRODUCAO_REGISTRO_ESTOQUE_ITEM rebuild
alter index  IDX_NOMECLIE on dbo.CLIENTE_GERAL reorganize
alter index  IDX_EXPECARGPICK on dbo.EXPEDICAO_CARGA_PICKING rebuild
alter index  IDX_EXPECARGPICK_2 on dbo.EXPEDICAO_CARGA_PICKING reorganize
alter index  IDX_N00969 on dbo.SISTEMA_USUARIO rebuild
alter index  IDX_N00970 on dbo.SISTEMA_USUARIO rebuild
alter index  IDX_N00971 on dbo.SISTEMA_USUARIO rebuild
alter index  IDX_N00972 on dbo.SISTEMA_USUARIO rebuild
alter index  IDX_N10169 on dbo.SISTEMA_USUARIO rebuild
alter index  IDX_N10170 on dbo.SISTEMA_USUARIO rebuild
alter index  IDX_N10171 on dbo.SISTEMA_USUARIO rebuild
alter index  IDX_N00938 on dbo.SCT_USUARIO_EMPRFILI rebuild
alter index  IDX_N00996 on dbo.TRANSPORTADOR_MOTORISTA rebuild
alter index  IDX_N00997 on dbo.TRANSPORTADOR_MOTORISTA reorganize
alter index  IDX_N00998 on dbo.TRANSPORTADOR_MOTORISTA rebuild
alter index  IDX_N00999 on dbo.TRANSPORTADOR_MOTORISTA rebuild
alter index  IDX_N10172 on dbo.TRANSPORTADOR_MOTORISTA rebuild
alter index  IDX_N10173 on dbo.TRANSPORTADOR_MOTORISTA rebuild
alter index  IDX_N10174 on dbo.TRANSPORTADOR_MOTORISTA rebuild
alter index  IDX_N00366 on dbo.GRANJA_PROPRIEDADE rebuild
alter index  IDX_N00367 on dbo.GRANJA_PROPRIEDADE rebuild
alter index  IDX_N00369 on dbo.GRANJA_PROPRIEDADE rebuild
alter index  IDX_N00370 on dbo.GRANJA_PROPRIEDADE rebuild
alter index  IDX_N00371 on dbo.GRANJA_PROPRIEDADE rebuild
alter index  IDX_N00372 on dbo.GRANJA_PROPRIEDADE rebuild
alter index  IDX_N00373 on dbo.GRANJA_PROPRIEDADE rebuild
alter index  IDX_N00374 on dbo.GRANJA_PROPRIEDADE rebuild
alter index  IDX_N00375 on dbo.GRANJA_PROPRIEDADE rebuild
alter index  DATA_PADRAO_REGISTRO_IDX_VW_PRO125 on dbo.DATA_PADRAO_REGISTRO rebuild
alter index  IDX_N00916 on dbo.SCT_DIREITOS_US_JANE reorganize
alter index  IDX_GRUP_DIREGRUPJANE on dbo.SCT_DIREITOS_GR_JANE rebuild
alter index  IDX_JANE_DIREGRUPJANE on dbo.SCT_DIREITOS_GR_JANE rebuild
alter index  IDX_MODU_DIREGRUPJANE on dbo.SCT_DIREITOS_GR_JANE rebuild
